server:
  port: 9001
  servlet:
    context-path: /user

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:11111/eureka/

spring:
  application.name: ggs-user-center
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/upp_order?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 15
      pool-name: GetDataHikariCP
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 10000
    password: 123456
    database: 0
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
feign:
  client:
    default:
      connectTimeout: 60000
      readTimeout: 60000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 别名包扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.ggs.user.center.provider.entity

  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 t_
    table-prefix: t_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 4
    logic-not-delete-value: 0

logging:
  level:
    com.ggs.user.center.provider.dao: debug